# Generated by Django 3.0.3 on 2020-04-04 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('other_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('mugshot', models.ImageField(blank=True, null=True, upload_to='teachers/images/%Y/%m/%d')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Rather Not Mention')], default='male', max_length=50)),
                ('date_of_birth', models.DateField(help_text='Format: YYYY-MM-DD')),
                ('date_admitted', models.DateField(help_text='Format: YYYY-MM-DD')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Teacher's Profile",
            },
        ),
    ]
